<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8MTXcVd\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8MTXcVd/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container8MTXcVd.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container8MTXcVd\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container8MTXcVd\appAppKernelProdContainer([
    'container.build_hash' => '8MTXcVd',
    'container.build_id' => '14ef7c0c',
    'container.build_time' => 1721294429,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8MTXcVd');
